name: End-to-end tests

on: 
   schedule:
    - cron: 0 15 * * * 

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v5
        
      - name: Generate report
        run:  cd cypress && npm run cy:report
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: cypress/cucumber-report/
        

      
      


